# Generated by Django 2.0.2 on 2018-03-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Аккаунт')),
                ('ip', models.CharField(max_length=100, unique=True, verbose_name='IP')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('authorized_network', models.CharField(blank=True, choices=[('vk', 'VK'), ('facebook', 'Facebook'), ('google', 'Google'), ('twitter', 'Twitter')], default='', max_length=12, verbose_name='Соц. сеть')),
                ('first_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Фамилия')),
                ('photo', models.URLField(blank=True, default='', max_length=255, verbose_name='Фотография')),
            ],
        ),
    ]
