# Generated by Django 2.0.2 on 2018-03-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0002_auto_20180306_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vk', 'VK'), ('facebook', 'Facebook'), ('google', 'Google'), ('twitter', 'Twitter')], max_length=12, verbose_name='Соц. сеть')),
                ('url', models.URLField(max_length=255, verbose_name='Ссылка в социальной сети')),
                ('account_name', models.CharField(max_length=150, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'лекция',
                'verbose_name_plural': 'лекции',
            },
        ),
    ]
