# Generated by Django 2.0.2 on 2018-03-06 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0003_lecture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('authorized_network', 'uid')},
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('type', 'url')},
        ),
    ]
