# Generated by Django 2.0.2 on 2018-03-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0004_auto_20180306_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='topic_id',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='id в соц. сети'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='type',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='url',
        ),
    ]
