# Generated by Django 2.0.2 on 2018-03-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0005_auto_20180306_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='authorized_network',
            field=models.CharField(choices=[('vk', 'VK'), ('facebook', 'Facebook'), ('google', 'Google')], max_length=12, verbose_name='Соц. сеть'),
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.URLField(default='', max_length=255, verbose_name='Фотография'),
        ),
    ]
