# Generated by Django 2.0.2 on 2018-03-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0006_auto_20180307_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='account_name',
        ),
        migrations.AddField(
            model_name='lecture',
            name='account',
            field=models.ForeignKey(default=None, on_delete='Аккаунт', to='faucet.Account'),
            preserve_default=False,
        ),
    ]
