# Generated by Django 2.0.2 on 2018-03-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0008_auto_20180307_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='account',
            new_name='account_name',
        ),
    ]
