# Generated by Django 2.0.2 on 2018-03-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0009_auto_20180307_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='authorized_network',
            field=models.CharField(choices=[('vk', 'VK'), ('facebook', 'Facebook'), ('google', 'Google')], max_length=12, null=True, verbose_name='Соц. сеть'),
        ),
        migrations.AlterField(
            model_name='account',
            name='ip',
            field=models.CharField(max_length=100, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.CharField(max_length=100, null=True, verbose_name='UID'),
        ),
    ]
